import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";

const cli = ["node", "dist/src/cli.js"] as const;
const gitEnv = {
  ...process.env,
  GIT_AUTHOR_NAME: "Mahler Test",
  GIT_AUTHOR_EMAIL: "test@example.com",
  GIT_COMMITTER_NAME: "Mahler Test",
  GIT_COMMITTER_EMAIL: "test@example.com"
};

function run(args: string[], cwd = process.cwd()): { status: number | null; stdout: string; stderr: string } {
  const result = spawnSync(cli[0], [cli[1], ...args], { cwd, encoding: "utf8" });
  return { status: result.status, stdout: result.stdout, stderr: result.stderr };
}

function initProductRepo(workspace: string): string {
  const repo = resolve(workspace, "app");
  const init = spawnSync("git", ["init", "-q", "-b", "main", repo], { encoding: "utf8" });
  assert.equal(init.status, 0, init.stderr);
  writeFileSync(resolve(repo, "README.md"), "# App\n");
  const add = spawnSync("git", ["-C", repo, "add", "README.md"], { encoding: "utf8" });
  assert.equal(add.status, 0, add.stderr);
  const commit = spawnSync("git", ["-C", repo, "commit", "-m", "init", "-q"], { encoding: "utf8", env: gitEnv });
  assert.equal(commit.status, 0, commit.stderr);
  return repo;
}

test("dogfood issue prompt workflow installs native artifacts and creates an issue workspace", () => {
  const workspace = mkdtempSync(resolve(tmpdir(), "mahler-dogfood-"));
  initProductRepo(workspace);

  const install = run(["install", workspace, "--linear-assignee", "gonzo", "--linear-label", "agent"]);
  assert.equal(install.status, 0, install.stderr);
  assert.match(install.stdout, /Installed Mahler workflow/);
  assert.match(install.stdout, /Configured 1 repo\(s\): app/);

  const config = JSON.parse(readFileSync(resolve(workspace, ".harness", "config.json"), "utf8")) as {
    repos: Array<{ name: string; path: string; baseBranch: string }>;
    linear: { acceptedAssignees: string[]; requiredLabels: string[] };
  };
  assert.deepEqual(config.repos, [{ name: "app", path: "app", baseBranch: "main", remote: "origin" }]);
  assert.deepEqual(config.linear.acceptedAssignees, ["gonzo"]);
  assert.deepEqual(config.linear.requiredLabels, ["agent"]);

  for (const path of [
    ".harness/policies/implementation.md",
    ".harness/agents/profiles/implementer.json",
    ".agents/skills/work-on-issue/SKILL.md",
    ".codex/agents/implementer.toml",
    ".claude/skills/work-on-issue/SKILL.md",
    ".claude/agents/implementer.md",
    "AGENTS.md",
    "CLAUDE.md",
    "WORKFLOW.md"
  ]) {
    assert.equal(existsSync(resolve(workspace, path)), true, `missing ${path}`);
  }

  const codexSkill = readFileSync(resolve(workspace, ".agents", "skills", "work-on-issue", "SKILL.md"), "utf8");
  assert.match(codexSkill, /^---\n/);
  assert.match(codexSkill, /name: work-on-issue/);
  assert.match(codexSkill, /Generated by Mahler/);
  const claudeSkill = readFileSync(resolve(workspace, ".claude", "skills", "work-on-issue", "SKILL.md"), "utf8");
  assert.match(claudeSkill, /name: work-on-issue/);
  assert.match(readFileSync(resolve(workspace, "AGENTS.md"), "utf8"), /<!-- HARNESS:START -->/);
  assert.match(readFileSync(resolve(workspace, "CLAUDE.md"), "utf8"), /<!-- HARNESS:START -->/);
  assert.match(readFileSync(resolve(workspace, "WORKFLOW.md"), "utf8"), /work on FUG-123/);

  const doctor = run(["doctor", workspace]);
  assert.equal(doctor.status, 0, doctor.stdout);
  assert.match(doctor.stdout, /repo app present/);
  assert.match(doctor.stdout, /Codex skill work-on-issue present/);
  assert.match(doctor.stdout, /Claude skill work-on-issue present/);

  const linearDir = resolve(workspace, ".harness", "tmp", "linear");
  const issuePath = resolve(linearDir, "MAH-5.json");
  mkdirSync(linearDir, { recursive: true });
  writeFileSync(
    issuePath,
    `${JSON.stringify(
      {
        id: "lin-mah-5",
        identifier: "MAH-5",
        title: "Add end-to-end dogfood test for issue prompt workflow",
        description: "Validate install, native artifacts, and issue workspace creation.",
        priority: 2,
        state: "Todo",
        stateType: "unstarted",
        assignee: "gonzo",
        assigneeName: "Gonzo",
        labels: ["agent"],
        blocked: false,
        updatedAt: "2026-05-22T23:02:34.302Z",
        createdAt: "2026-05-22T00:46:37.740Z",
        url: "https://linear.app/ilusiv/issue/MAH-5/add-end-to-end-dogfood-test-for-issue-prompt-workflow"
      },
      null,
      2
    )}\n`
  );

  const issue = run(["issue", "MAH-5", "--workspace", workspace, "--agent", "codex", "--linear-file", issuePath]);
  assert.equal(issue.status, 0, issue.stderr);
  assert.match(issue.stdout, /Issue workspace ready:/);
  assert.match(issue.stdout, /workspaces\/issues\/MAH-5/);
  assert.match(issue.stdout, /Launch command:/);
  assert.match(issue.stdout, /codex --cd/);

  const issueWorkspace = resolve(workspace, "workspaces", "issues", "MAH-5");
  for (const path of ["TASK.md", "AGENT_SESSION.md", "HANDOFF.md", "linear-issue.json", "repos/app"]) {
    assert.equal(existsSync(resolve(issueWorkspace, path)), true, `missing issue artifact ${path}`);
  }
  assert.match(readFileSync(resolve(issueWorkspace, "TASK.md"), "utf8"), /Linear source: linear-file/);
  assert.match(readFileSync(resolve(issueWorkspace, "AGENT_SESSION.md"), "utf8"), /Profile: implementer/);
  assert.match(readFileSync(resolve(issueWorkspace, "HANDOFF.md"), "utf8"), /State: not started/);

  const issueJson = JSON.parse(readFileSync(resolve(issueWorkspace, "linear-issue.json"), "utf8")) as { identifier: string; title: string };
  assert.equal(issueJson.identifier, "MAH-5");
  assert.equal(issueJson.title, "Add end-to-end dogfood test for issue prompt workflow");

  const worktreeBranch = spawnSync("git", ["-C", resolve(issueWorkspace, "repos", "app"), "branch", "--show-current"], {
    encoding: "utf8"
  });
  assert.equal(worktreeBranch.status, 0, worktreeBranch.stderr);
  assert.equal(worktreeBranch.stdout.trim(), "MAH-5");
});
