import test from "node:test";
import assert from "node:assert/strict";
import { capacityReport } from "../src/commands/capacity.js";
import { defaultConcurrency, defaultModels } from "../src/config.js";
import {
  agentNameCollisions,
  defaultModelFor,
  modelConfigProblems,
  modelOverrides,
  resolveModels,
  tierVariants,
} from "../src/models.js";
import { modelsMarkdown } from "../src/render.js";
import { profileNames } from "../src/scaffold.js";

test("default models config is consistent with the canonical profiles", () => {
  assert.deepEqual(modelConfigProblems(defaultModels(), profileNames()), []);
});

test("defaultModelFor pins model and effort, but not skill or agent routes", () => {
  const models = defaultModels();
  assert.deepEqual(defaultModelFor(models, "reviewer", "claude"), {
    model: "sonnet",
    effort: "high",
  });
  assert.deepEqual(defaultModelFor(models, "reviewer", "codex"), {
    model: "gpt-6.1-sol",
    effort: "medium",
  });
  // Profiles a human talks to inherit the session's model.
  assert.equal(defaultModelFor(models, "conductor", "claude")?.model, "inherit");
  assert.equal(defaultModelFor(models, "composer", "codex")?.model, undefined);
  models.tiers.cross = { claude: { skill: "codex:review" } };
  models.profiles.reviewer = { default: "cross", allowed: ["cross"] };
  assert.equal(defaultModelFor(models, "reviewer", "claude"), undefined);
  assert.equal(defaultModelFor(models, "unknown", "claude"), undefined);
});

test("tierVariants covers each other allowed tier with different settings, per runtime", () => {
  const models = defaultModels();
  assert.deepEqual(
    tierVariants(models, "conductor", "claude").map((v) => [v.name, v.choice]),
    [
      ["conductor-trivial", { model: "haiku", effort: "high" }],
      ["conductor-light", { model: "sonnet", effort: "high" }],
      ["conductor-standard", { model: "opus", effort: "medium" }],
      ["conductor-deep", { model: "opus", effort: "high" }],
    ],
  );
  // Codex applies an agent's settings over spawn values, so it gets variants too.
  assert.deepEqual(
    tierVariants(models, "reviewer", "codex").map((v) => [v.name, v.choice]),
    [
      ["reviewer-trivial", { model: "gpt-6-luna", effort: "high" }],
      ["reviewer-standard", { model: "gpt-6.1-sol", effort: "high" }],
      ["reviewer-deep", { model: "gpt-6-astra", effort: "high" }],
    ],
  );
  // Composer allows only its default tier.
  assert.deepEqual(tierVariants(models, "composer", "claude"), []);
  // Skill routes and tiers identical to the default get no definition.
  models.tiers.cross = { claude: { skill: "codex:review" } };
  models.tiers.same = { claude: { model: "sonnet", effort: "high" } };
  models.profiles.reviewer.allowed = ["light", "cross", "same", "deep", "inherit"];
  assert.deepEqual(
    tierVariants(models, "reviewer", "claude").map((v) => [v.name, v.choice.model]),
    [["reviewer-deep", "opus"], ["reviewer-inherit", "inherit"]],
  );
});

test("a tier left empty for a runtime gets an unpinned variant that inherits", () => {
  const models = resolveModels(defaultModels(), { tiers: { deep: { claude: null, codex: {} } } });
  const claude = tierVariants(models, "reviewer", "claude").find((v) => v.tier === "deep");
  assert.deepEqual(claude?.choice, { model: "inherit" });
  const codex = tierVariants(models, "reviewer", "codex").find((v) => v.tier === "deep");
  assert.deepEqual(codex?.choice, {});
});

test("agentNameCollisions catches two tier agents with the same name", () => {
  const models = resolveModels(defaultModels(), {
    tiers: { "cross-deep": { claude: { model: "opus" }, codex: { model: "gpt-6-astra" } } },
    profiles: {
      reviewer: { allowed: ["light", "cross-deep"] },
      "reviewer-cross": { default: "light", allowed: ["light", "deep"] },
    },
  });
  const problems = agentNameCollisions(models, ["reviewer", "reviewer-cross"]).join("\n");
  assert.match(problems, /agent "reviewer-cross-deep" would be generated by reviewer at the cross-deep tier and reviewer-cross at the deep tier/);
  assert.deepEqual(agentNameCollisions(defaultModels(), ["composer", "conductor", "reviewer"]), []);
});

test("modelConfigProblems flags bad efforts, undefined tiers, and mixed routes", () => {
  const models = defaultModels();
  models.tiers.light.codex = { effort: "turbo" };
  models.tiers.inherit = { claude: { model: "opus" } };
  models.tiers.odd = { claude: { skill: "codex:review", model: "opus" } };
  models.profiles.reviewer = { default: "missing", allowed: ["light"] };
  const problems = modelConfigProblems(models, profileNames()).join("\n");
  assert.match(problems, /light\.codex\.effort "turbo"/);
  assert.match(problems, /models\.tiers\.inherit is reserved/);
  assert.match(problems, /ignores model and effort/);
  assert.match(problems, /undefined tier "missing"/);
  assert.match(problems, /not in its allowed list/);
});

test("capacityReport says busy above the per-core threshold and ok below it", () => {
  const caps = defaultConcurrency();
  const busy = capacityReport(caps, { cores: 4, load: [4, 3, 2] });
  assert.match(busy, /verdict: busy/);
  const ok = capacityReport(caps, { cores: 10, load: [2, 2, 2] });
  assert.match(ok, /verdict: ok — about 6 core\(s\) of headroom/);
  const unknown = capacityReport(caps, { cores: 8 });
  assert.match(unknown, /load: unavailable/);
});

test("resolveModels applies overrides per tier runtime and per profile field", () => {
  const defaults = defaultModels();
  const models = resolveModels(defaults, {
    tiers: {
      deep: { codex: { model: "gpt-7", effort: "xhigh" } },
      trivial: null,
      light: { codex: null },
      "cross-check": { claude: { skill: "codex:review" } },
    },
    profiles: {
      reviewer: { default: "cross-check" },
      composer: null,
    },
  });
  // A runtime entry replaces the default's; the other runtime keeps its default.
  assert.deepEqual(models.tiers.deep, {
    claude: { model: "opus", effort: "high" },
    codex: { model: "gpt-7", effort: "xhigh" },
  });
  assert.equal(models.tiers.trivial, undefined);
  assert.deepEqual(models.tiers.light, { claude: { model: "sonnet", effort: "high" } });
  assert.deepEqual(models.tiers["cross-check"], { claude: { skill: "codex:review" } });
  // Profile fields merge: default changes, allowed keeps the default list.
  assert.deepEqual(models.profiles.reviewer, {
    default: "cross-check",
    allowed: defaults.profiles.reviewer.allowed,
  });
  assert.equal(models.profiles.composer, undefined);
});

test("modelOverrides is the minimal diff, and round-trips through resolveModels", () => {
  const defaults = defaultModels();
  assert.deepEqual(modelOverrides(defaults, defaults), { tiers: {}, profiles: {} });
  const overrides = {
    tiers: { deep: { codex: { model: "gpt-7", effort: "xhigh" } }, trivial: null },
    profiles: { reviewer: { allowed: ["light", "deep"] }, composer: null },
  };
  const models = resolveModels(defaults, overrides);
  assert.deepEqual(modelOverrides(defaults, models), overrides);
  // An override equal to the default is dropped, so the install follows future defaults.
  const redundant = resolveModels(defaults, { tiers: { light: { claude: { model: "sonnet", effort: "high" } } } });
  assert.deepEqual(modelOverrides(defaults, redundant), { tiers: {}, profiles: {} });
  // A tier the install added survives even with no runtime entries.
  const native = resolveModels(defaults, {
    tiers: { native: {} },
    profiles: { reviewer: { allowed: ["light", "native"] } },
  });
  assert.deepEqual(modelOverrides(defaults, native).tiers, { native: {} });
});

test("a command route pins nothing, gets no tier agent, and is validated", () => {
  const command = "node companion.mjs review --wait --cwd <worktree> --base <base> | tee review.txt";
  const models = resolveModels(defaultModels(), {
    tiers: { "cross-check": { claude: { command }, codex: { model: "gpt-6.1-sol", effort: "high" } } },
    profiles: { reviewer: { default: "cross-check", allowed: ["light", "cross-check"] } },
  });
  assert.equal(defaultModelFor(models, "reviewer", "claude"), undefined);
  assert.deepEqual(tierVariants(models, "reviewer", "claude").map((v) => v.name), ["reviewer-light"]);
  assert.deepEqual(modelConfigProblems(models, ["composer", "conductor", "reviewer"]), []);
  const doc = modelsMarkdown(models, ["reviewer"]);
  assert.ok(doc.includes("| `cross-check` | command: `node companion.mjs review --wait --cwd <worktree> --base <base> \\| tee review.txt` |"));
  assert.match(doc, /cross-check: command \(see Tiers\)/);

  models.tiers.bad = { claude: { command: "x", skill: "y", model: "opus" } };
  const problems = modelConfigProblems(models, ["reviewer"]).join("\n");
  assert.match(problems, /bad\.claude sets skill and command; pick one/);
  assert.match(problems, /bad\.claude routes to a skill, which ignores model and effort/);
});
