import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { installVersionFinding } from "../src/commands/doctor.js";
import { mahlerVersion } from "../src/util.js";

const pkgVersion = JSON.parse(readFileSync("package.json", "utf8")).version as string;

test("mahler --version prints the package version", () => {
  assert.equal(mahlerVersion(), pkgVersion);
  const result = spawnSync("node", ["dist/src/cli.js", "--version"], { encoding: "utf8" });
  assert.equal(result.status, 0);
  assert.equal(result.stdout.trim(), pkgVersion);
});

test("install records the Mahler version, and doctor compares it with the CLI", () => {
  const workspace = mkdtempSync(resolve(tmpdir(), "mahler-version-"));
  assert.equal(spawnSync("node", ["dist/src/cli.js", "install", workspace]).status, 0);
  const harness = resolve(workspace, ".harness");
  assert.deepEqual(JSON.parse(readFileSync(resolve(harness, "install.json"), "utf8")), {
    mahlerVersion: pkgVersion,
  });
  assert.equal(installVersionFinding(harness).level, "ok");

  const stale = installVersionFinding(harness, "9.9.9");
  assert.equal(stale.level, "warn");
  assert.match(stale.message, new RegExp(`generated by Mahler ${pkgVersion.replaceAll(".", "\\.")}, but this CLI is 9\\.9\\.9`));

  writeFileSync(resolve(harness, "install.json"), "{}\n");
  assert.match(installVersionFinding(harness).message, /no record of which Mahler generated this workspace/);
});
